import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { getTranslations, t } from '@/features/i18n/config/get-translations';
import type { Locale } from '@/features/i18n/types/types';
import { siteConfig } from '@/lib/config/site';

const HeroSection = ({ locale }: { locale: Locale }) => {
  const messages = getTranslations(locale);
  const isRtl = locale === 'ar';

  const features = [
    {
      icon: '🌐',
      title: 'Global-Ready i18n',
      description: t(messages, 'home.features.typeSafe'),
      details: [
        'Type-safe multi-language support',
        'English, Bengali, and Arabic',
        'Automated RTL layout engine',
      ],
    },
    {
      icon: '🔐',
      title: 'Secure Auth & RBAC',
      description: t(messages, 'home.features.rbac'),
      details: [
        'NextAuth.js + Google & Social OAuth',
        'Multi-tier Role-Based Access',
        'Secure parallel & intercepted routes',
      ],
    },
    {
      icon: '📄',
      title: 'Centralized Orchestration',
      description: t(messages, 'home.features.production'),
      details: [
        'Single-source configuration engine',
        'Unified SEO, i18n, and metadata',
        'Dynamic environment overrides',
      ],
    },
    {
      icon: '🚀',
      title: 'Elite Tech Stack',
      description: t(messages, 'home.features.stack'),
      details: [
        'Next.js 16 (App Router) & React 19',
        'Advanced TypeScript orchestration',
        'Tailwind CSS 4 + shadcn/ui',
      ],
    },
    {
      icon: '🎨',
      title: 'Dynamic Design System',
      description: t(messages, 'home.features.ui-experience'),
      details: [
        'Smart dark/light/system modes',
        'Micro-interactions & transitions',
        'Fully responsive fluid layouts',
      ],
    },
    {
      icon: '🔍',
      title: 'Advanced SEO & PWA',
      description: t(messages, 'home.features.seo'),
      details: [
        'Dynamic JSON-LD & OpenGraph',
        'Autogenerated sitemaps & robots.txt',
        'Standardized PWA manifest',
      ],
    },
  ];

  return (
    <div
      className={`mx-auto max-w-7xl px-4 py-12 ${isRtl ? 'text-right' : 'text-left'}`}
    >
      <Card className="mb-6 transition-shadow hover:shadow-lg">
        <CardContent className="py-6">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <h1 className="bg-linear-to-r from-primary to-primary/60 bg-clip-text text-5xl font-bold text-transparent">
                Next.js Elite Boilerplate
              </h1>
              {siteConfig.tagline && (
                <p className="mt-2 text-lg text-muted-foreground">
                  {siteConfig.tagline}
                </p>
              )}
            </div>
            <a
              href="https://github.com/salmanshahriar/Nextjs-Elite-Boilerplate"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 rounded-lg bg-secondary px-6 py-6 text-lg font-medium text-secondary-foreground transition-colors hover:bg-secondary/80"
            >
              💻 Source code (GitHub)
            </a>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
        {features.map((feature, index) => (
          <Card key={index} className="transition-shadow hover:shadow-lg">
            <CardHeader>
              <div className="flex items-center gap-2">
                <span className="text-2xl">{feature.icon}</span>
                <CardTitle className="text-lg">{feature.title}</CardTitle>
              </div>
            </CardHeader>
            <CardContent>
              {feature.description && (
                <p className="mb-3 text-sm text-muted-foreground">
                  {feature.description}
                </p>
              )}
              <ul className="space-y-1">
                {feature.details.map((detail, i) => (
                  <li
                    key={i}
                    className="flex items-center gap-2 text-xs text-muted-foreground"
                  >
                    <span className="text-primary">✓</span>
                    {detail}
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
};

export default HeroSection;
